Repository kubernetes/dns, pull requests merged in 2018-03, with the labels that each got.

#206 Fix travis: include vendor folder in build.sh
  build/build.sh
Labels: cncf-cla: yes, size/XS

#219 Implement HasSynced() of skydns Backend interface
  Godeps/Godeps.json
  pkg/dns/dns.go
  vendor/github.com/skynetservices/skydns/server/backend.go
  vendor/github.com/skynetservices/skydns/server/server.go
Labels: cncf-cla: yes, lgtm, size/S

#210 fix bug with delete externalName service
  pkg/dns/dns.go
Labels: cncf-cla: yes, lgtm, size/XS

#197 Separate the initialization logs for each resource
  pkg/dns/dns.go
Labels: cncf-cla: yes, lgtm, size/S
