Repository kubernetes/dns, pull requests merged in 2018-04, with the labels that each got.

#220 Forward PTR record lookup from kubedns to upstream server.
  cmd/kube-dns/app/server.go
  cmd/kube-dns/app/server_test.go
  pkg/dns/config/config.go
  pkg/dns/dns.go
  pkg/dns/util/util.go
  pkg/dns/util/util_test.go
  pkg/e2e/dns/dns.go
  pkg/e2e/options.go
  test/e2e/kubedns/kubedns.go
Labels: cncf-cla: yes, lgtm, size/L

#223 Pass 2: k8s GCR vanity URL
  images/dnsmasq/Makefile
Labels: cncf-cla: yes, lgtm, size/XS

#225 Fix external name not solving by reloading resolv.conf.
  cmd/kube-dns/app/server.go
  pkg/dns/dns.go
  pkg/dns/dns_test.go
Labels: cncf-cla: yes, lgtm, size/M
