Repository kubernetes/dns, pull requests merged in 2019-04, with the labels that each got.

#294 Rebase container images from alpine to distroless.
  Dockerfile.node-cache
  rules.mk
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#296 Rebase dnsmasq images from busybox to debian-base.
  images/dnsmasq/Makefile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#291 Add retry logic when iptables checks fail
  Gopkg.lock
  cmd/node-cache/main.go
  cmd/node-cache/metrics.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#297 Fix the compile image of dnsmasq.
  images/dnsmasq/Makefile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#299 Node cache: Make metrics listen address configurable
  cmd/node-cache/main.go
Labels: approved, cncf-cla: yes, lgtm, size/S
