Repository kubernetes/dns, pull requests merged in 2019-01, with the labels that each got.

#284 Check error for SetDefaults()
  cmd/kube-dns/app/server.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#279 allow service name for stubDomains
  cmd/dnsmasq-nanny/main.go
  pkg/dnsmasq/nanny.go
  pkg/dnsmasq/nanny_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#286 Run checks before starting CoreDNS
  cmd/node-cache/main.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#287 Adding myself to OWNERS
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS
