Repository kubernetes/dns, pull requests merged in 2020-12, with the labels that each got.

#418 Add ipv6 support to node-local-dns
  cmd/node-cache/app/cache_app.go
  cmd/node-cache/app/cache_app_test.go
  cmd/node-cache/main.go
  pkg/dns/config/config.go
  pkg/dns/config/config_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#426 Add coredns trace plugin to node-cache.
  cmd/node-cache/main.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#424 Add support for rewrite plugin in node-cache
  cmd/node-cache/main.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#428 Fix error string should not be capitalized and sort import
  cmd/node-cache/app/cache_app.go
  cmd/node-cache/main.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#429 Trans exitchan elm type to struct
  cmd/node-cache/app/cache_app.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
