Repository kubernetes/dns, pull requests merged in 2020-02, with the labels that each got.

#342 Debian base uses `nogroup` as the group
  Dockerfile.sidecar
Labels: approved, cncf-cla: yes, lgtm, size/XS

#345 Fix build instructions
  README.md
  rules.mk
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#348 modify cache_app_test to sleep for more time.
  cmd/node-cache/app/cache_app_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#340 Fixed negative Prometheus counter panic in DNS sidecar.
  pkg/sidecar/server.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#344 Add loadbalance, whoami plugins
  Gopkg.lock
  cmd/node-cache/main.go
  vendor/github.com/coredns/coredns/plugin/loadbalance/README.md
  vendor/github.com/coredns/coredns/plugin/loadbalance/handler.go
  vendor/github.com/coredns/coredns/plugin/loadbalance/loadbalance.go
  vendor/github.com/coredns/coredns/plugin/loadbalance/setup.go
  vendor/github.com/coredns/coredns/plugin/whoami/README.md
  vendor/github.com/coredns/coredns/plugin/whoami/fuzz.go
  vendor/github.com/coredns/coredns/plugin/whoami/setup.go
  vendor/github.com/coredns/coredns/plugin/whoami/whoami.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L
