Repository kubernetes/dns, pull requests merged in 2020-03, with the labels that each got.

#352 skip conntrack for node-local-dns healthchecks
  cmd/node-cache/app/cache_app.go
  cmd/node-cache/main.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#353 Reuse the setup networking function in node-cache.
  cmd/node-cache/app/cache_app.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#354 Add a flag to skip teardown in node-cache.
  cmd/node-cache/app/cache_app.go
  cmd/node-cache/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#355 Use debian-iptables-$(ARCH):v12.0.1 and debian-base-$(ARCH):v2.0.0
  Dockerfile.node-cache
  images/dnsmasq/Makefile
  rules.mk
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#361 Fix skipteardown flag not completely avoiding teardown
  cmd/node-cache/app/cache_app.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS
