Repository kubernetes/dns, pull requests merged in 2020-05, with the labels that each got.

#377 Use UDP to contact stubDomains and custom upstream servers from node-cache.
  cmd/node-cache/app/cache_app.go
  cmd/node-cache/app/cache_app_test.go
  cmd/node-cache/app/configmap.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#378 Include template plugin in vendor.
  Gopkg.lock
  vendor/github.com/coredns/coredns/plugin/pkg/fall/fall.go
  vendor/github.com/coredns/coredns/plugin/pkg/upstream/upstream.go
  vendor/github.com/coredns/coredns/plugin/template/README.md
  vendor/github.com/coredns/coredns/plugin/template/metrics.go
  vendor/github.com/coredns/coredns/plugin/template/setup.go
  vendor/github.com/coredns/coredns/plugin/template/template.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#379 Declare all substitution strings as constants in node-cache
  cmd/node-cache/app/cache_app_test.go
  cmd/node-cache/app/configmap.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#380 chore(Makefile): update base image
  images/dnsmasq/Makefile
  rules.mk
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS
