Repository kubernetes/dns, pull requests merged in 2020-04, with the labels that each got.

#363 Improve Prometheus metrics for node-cache
  cmd/node-cache/app/metrics.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#364 Added cloudbuild.yaml to push dns images.
  Makefile
  README.md
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#366 Revert "Use debian-iptables-$(ARCH):v12.0.1 and debian-base-$(ARCH):v2.0.0"
  Dockerfile.node-cache
  images/dnsmasq/Makefile
  rules.mk
Labels: approved, cncf-cla: yes, lgtm, size/M

#368 Added a simple script to sanity check dns images.
  image-checks.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#369 Add configmap error metric
  cmd/node-cache/app/configmap.go
  cmd/node-cache/app/metrics.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#370 Use debian-base-$(ARCH):v2.0.0 as base image
  Dockerfile.node-cache
  images/dnsmasq/Makefile
  rules.mk
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#371 Set version variable in build script, if not set.
  build/build.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#372 Revert "Set version variable in build script, if not set."
  build/build.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#373 Add a VERSION env var in cloudbuild.
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#375 Add extra space in sha check command
  images/dnsmasq/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#374 Include template plugin in node-cache.
  cmd/node-cache/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
