Repository kubernetes/dns, pull requests merged in 2020-10, with the labels that each got.

#407 Adds option to NOT set up interface when deployed in non-root ns.
  cmd/node-cache/app/cache_app.go
  cmd/node-cache/main.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#411 update the dnsmasq base image to debian v2.1.2
  images/dnsmasq/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#412 Update the compile image to debian v2.1.2
  images/dnsmasq/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#367 Use debian-iptables for k8s-dns-node-cache, bump debian-base version
  Dockerfile.kube-dns
  Dockerfile.node-cache
  Dockerfile.sidecar
  images/dnsmasq/Makefile
  rules.mk
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S
