Repository kubernetes/dns, pull requests merged in 2021-11, with the labels that each got.

#488 Increment error metric for rule deletion errors as well.
  cmd/node-cache/app/cache_app.go
  cmd/node-cache/app/metrics.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#490 images: use k8s-staging-test-infra/gcb-docker-gcloud
  cloudbuild.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#491 images: fix invalid k8s-staging-test-infra/gcb-docker-gcloud tag
  cloudbuild.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#489 Add the dns64 plugin to node-cache
  cmd/node-cache/main.go
  go.mod
  go.sum
  vendor/github.com/coredns/coredns/plugin/dns64/README.md
  vendor/github.com/coredns/coredns/plugin/dns64/dns64.go
  vendor/github.com/coredns/coredns/plugin/dns64/metrics.go
  vendor/github.com/coredns/coredns/plugin/dns64/setup.go
  vendor/modules.txt
Labels: cncf-cla: yes, lgtm, size/XL, approved
