Repository kubernetes/dns, pull requests merged in 2021-06, with the labels that each got.

#457 Add a new presubmit script for k/dns PRs.
  presubmits.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#462 Increase verbosity of presubmit script
  README.md
  presubmits.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#459 Update README with presubmit info.
  README.md
Labels: approved, cncf-cla: yes, size/XS

#463 Add more presubmit commands to DNS Presubmit
  presubmits.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#464 Include ginkgo tests in presubmit
  presubmits.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#465 Install and invoke sudo before ginkgo test
  presubmits.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#456 Update debian-iptables and debian-base images.
  images/dnsmasq/Makefile
  rules.mk
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS
