Repository kubernetes/dns, pull requests merged in 2021-05, with the labels that each got.

#449 Avoid delaying startup by SyncInterval for initial iptables/ebtables setup
  cmd/node-cache/app/cache_app.go
  cmd/node-cache/main.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#450 Increase build timeout to 2 hours.
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#446 Upgrade to dnsmasq 2.85.
  images/dnsmasq/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/S
