Repository kubernetes/dns, pull requests merged in 2021-07, with the labels that each got.

#468 467 remove setupebtables option
  Dockerfile.node-cache
  cmd/node-cache/app/cache_app.go
  cmd/node-cache/main.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#469 replacing master with main for k/k8s.io links
  README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#470 update debian base for vuln fixes.
  images/dnsmasq/Makefile
  rules.mk
Labels: approved, cncf-cla: yes, lgtm, size/XS

#471 Remove broken link
  README.md
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/XS

#473 Update README.md with build command for node-cache.
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS
