Repository kubernetes/dns, pull requests merged in 2022-11, with the labels that each got.

#552 Upgraded to the latest golang crypto package for vuln fixes
  go.mod
  go.sum
  vendor/modules.txt
Labels: cncf-cla: yes, lgtm, size/M, approved

#554 refactor: move from io/ioutil to io and os packages
  cmd/node-cache/app/cache_app_test.go
  cmd/node-cache/app/configmap.go
  cmd/sidecar-e2e/main.go
  pkg/dns/config/sync_dir.go
  pkg/dns/config/sync_dir_test.go
  pkg/dns/dns_test.go
  pkg/e2e/dnsmasq/nanny.go
  test/e2e/kubedns/kubedns.go
  third_party/forked/skydns/server/metrics_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test

#556 Switch distroless-iptables to gke-release
  rules.mk
Labels: cncf-cla: yes, lgtm, size/XS, approved
