Repository kubernetes/dns, pull requests merged in 2025-05, with the labels that each got.

#644 Send SIGUSR1 to dnsmasq periodically
  cmd/dnsmasq-nanny/main.go
  pkg/dnsmasq/nanny.go
  pkg/dnsmasq/nanny_test.go
  test/fixtures/mock-dnsmasq.sh
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test

#685 Update distroless static-debian12 image
  rules.mk
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#686 Bump Go dependency to fix CVE-2025-22872
  go.mod
  go.sum
  vendor/golang.org/x/net/html/atom/table.go
  vendor/golang.org/x/net/html/parse.go
  vendor/golang.org/x/net/html/token.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/golang.org/x/sync/errgroup/go120.go
  vendor/golang.org/x/sync/errgroup/pre_go120.go
  vendor/golang.org/x/text/language/parse.go
  vendor/modules.txt
Labels: cncf-cla: yes, lgtm, approved, size/XXL, ok-to-test

#688 Bump base images
  images/dnsmasq/Makefile
  rules.mk
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#696 Enhance dependabot configuration
  .github/dependabot.yml
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test
